services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce
    volumes:
      - ./postgres_data:/var/lib/postgresql/data